import{i,a as b,S as L}from"./assets/vendor-b725de7c.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const $="https://pixabay.com",S="api/",w="41917701-79d925887e26991e7dbaf3a79",d=document.querySelector(".gallery-form"),m=document.querySelector(".loader"),f=document.querySelector(".gallery"),g=document.querySelector(".massege"),u=document.querySelector(".button-load");let l=1,y="";const p=40;let a="";d.addEventListener("submit",function(s){s.preventDefault();const{name:o}=d.elements;a=o.value.trim(),m.style.display="block",a?o.value.length<3&&i.error({title:"Error",message:"Search string must be not less then 3 symbols."}):i.error({title:"Error",message:"Please fill search string before submitting."}),l=1,y="",h(a,l),d.reset()});async function h(s,o){const r=encodeURIComponent(s),n=`${$}/${S}?key=${w}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${p}&page=${o}`;console.log(n);try{const t=(await b.get(n)).data;console.log(t),m.style.display="none",u.style.display="none",g.style.display="none",t.hits&&t.hits.length>0?(t.totalHits>o*p?u.style.display="block":g.style.display="block",k(t.hits)):(f.innerHTML="",i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}))}catch(e){i.error({title:"Error",message:"Error fetching images: ${error}"}),console.error("Error fetching images:",e)}}function k(s){y+=s.map(r=>`<li class="gallery-item">
      <a class="gallery-link" href="${r.largeImageURL}">
        <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
      </a>
    <p>Likes: ${r.likes}</p>
    <p>Views: ${r.views}</p>
    <p>Comments: ${r.comments}</p>
    <p>Downloads: ${r.downloads}</p>
    </li>`).join(""),f.innerHTML=y,new L(".gallery a",{animationSpeed:250,captionsData:"alt",captionDelay:250}).refresh()}u.addEventListener("click",function(){m.style.display="block",l=l+1;const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),h(a,l)});
//# sourceMappingURL=commonHelpers.js.map
